version: '3.8'
services:
  web:
    container_name: blue-vending-machine-fe
    image: nginx:latest
    context: ..
    ports:
      - '8085:80'
    restart: always
  # api:
  #   container_name: blue-vending-machine-be
  #   image: nginx:latest
  #   context: ..
  #   ports:
  #     - '8086:80'
  #   restart: always
  postgres:
    image: postgres
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
    restart: always
