/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./public/index.html', './app/**/*.{ts,tsx,css}'],
  presets: [],
  prefix: '',
  theme: {
    screens: {
      sm: '320px',
      md: '425px',
      lg: '1024px',
      xl: '1440px',
      '2xl': '1920px',
    },
    container: {
      center: 'true',
    },
    extend: {},
    plugins: [
      require('tailwindcss-animate'),
      ({ addUtilities }) => {
        addUtilities({
          '.typography-heading-1': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '36px',
            'font-weight': 'bold',
            'line-height': '48px',
            'letter-spacing': '0px',
          },
          '.typography-heading-2': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '28px',
            'font-weight': 'bold',
            'line-height': '36px',
            'letter-spacing': '0px',
          },
          '.typography-heading-3': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '21px',
            'font-weight': 'bold',
            'line-height': '30px',
            'letter-spacing': '0px',
          },
          '.typography-heading-4': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '18px',
            'font-weight': 'bold',
            'line-height': '26px',
            'letter-spacing': '0px',
          },
          '.typography-heading-5': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '16px',
            'font-weight': 'bold',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-heading-6': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '14px',
            'font-weight': 'bold',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-label-1': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '16px',
            'font-weight': 'bold',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-label-2': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '14px',
            'font-weight': 'bold',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-label-3': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '12px',
            'font-weight': 'bold',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-caption-1': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '21px',
            'font-weight': '500',
            'line-height': '30px',
            'letter-spacing': '0px',
          },
          '.typography-caption-2': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '18px',
            'font-weight': '500',
            'line-height': '26px',
            'letter-spacing': '0px',
          },
          '.typography-caption-3': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '16px',
            'font-weight': '500',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-caption-4': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '14px',
            'font-weight': '500',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-caption-5': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '12px',
            'font-weight': '500',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-body-1': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '16px',
            'font-weight': 'normal',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-body-2': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '14px',
            'font-weight': 'normal',
            'line-height': '22px',
            'letter-spacing': '0px',
          },
          '.typography-body-3': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '12px',
            'font-weight': 'normal',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-support-1': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '10px',
            'font-weight': 'bold',
            'line-height': '14px',
            'letter-spacing': '0px',
          },
          '.typography-support-2': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '10px',
            'font-weight': '500',
            'line-height': '14px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-medium-1': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '21px',
            'font-weight': '500',
            'line-height': '28px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-medium-2': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '16px',
            'font-weight': '500',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-medium-3': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '14px',
            'font-weight': '500',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-medium-4': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '12px',
            'font-weight': '500',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-medium-5': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '10px',
            'font-weight': '500',
            'line-height': '14px',
            'letter-spacing': '0px',
          },
          '.typography-strikethrough-1': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '14px',
            'font-weight': 'normal',
            'line-height': '20px',
            'letter-spacing': '0px',
            'text-decoration': 'line-through',
          },
          '.typography-strikethrough-2': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '12px',
            'font-weight': 'normal',
            'line-height': '18px',
            'letter-spacing': '0px',
            'text-decoration': 'line-through',
          },
          '.typography-strikethrough-3': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '10px',
            'font-weight': 'normal',
            'line-height': '14px',
            'letter-spacing': '0px',
            'text-decoration': 'line-through',
          },
          '.typography-numeric-regular-1': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '21px',
            'font-weight': 'normal',
            'line-height': '28px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-regular-2': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '16px',
            'font-weight': 'normal',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-regular-3': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '14px',
            'font-weight': 'normal',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-regular-4': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '12px',
            'font-weight': 'normal',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-numeric-regular-5': {
            'text-indent': '0px',
            'font-family': 'IBM-Poppins',
            'font-size': '10px',
            'font-weight': 'normal',
            'line-height': '14px',
            'letter-spacing': '0px',
          },
          '.typography-link-bold-1': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '16px',
            'font-weight': 'bold',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-link-bold-2': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '14px',
            'font-weight': 'bold',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-link-bold-3': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '12px',
            'font-weight': 'bold',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-link-bold-4': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '10px',
            'font-weight': 'bold',
            'line-height': '14px',
            'letter-spacing': '0px',
          },
          '.typography-link-medium-1': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '16px',
            'font-weight': '500',
            'line-height': '24px',
            'letter-spacing': '0px',
          },
          '.typography-link-medium-2': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '14px',
            'font-weight': '500',
            'line-height': '20px',
            'letter-spacing': '0px',
          },
          '.typography-link-medium-3': {
            'text-indent': ' 0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '12px',
            'font-weight': '500',
            'line-height': '18px',
            'letter-spacing': '0px',
          },
          '.typography-link-medium-4': {
            'text-indent': '0px',
            'font-family': 'IBM Plex Sans Thai',
            'font-size': '10px',
            'font-weight': '500',
            'line-height': '14px',
            'letter-spacing': '0px',
          },
        });
      },
    ],
  },
};
